import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const EXTRA_HEAD_TAGS = process.env.NEXT_PUBLIC_EXTRA_HEAD_TAGS;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     <body className="bg-black text-white">
      {EXTRA_HEAD_TAGS && (
        <div
          id="analytics-head-tags"
          style={{ display: "none" }}
          dangerouslySetInnerHTML={{ __html: EXTRA_HEAD_TAGS }}
        />
      )}
      {children}
      </body>
    </html>
  );
}
